[package]
name = "tokio-aead"
version = "0.0.0"
authors = [ "Arthur Gautier" ]

[dependencies]
futures = "0.1"
bytes = "0.4"
chacha20-poly1305-aead = "0.1"
rand = "0.5"
log = "0.4.6"

[dev-dependencies]
stderrlog = "0.4.1"
